site_name: Flux HvH™帮助文档
site_url: https://docs.cshvh.cn/
site_author: Flux-Team
copyright: |
  Copyright &copy; FluxHvH 团队 2024
  鲁ICP备2024091044号-1
theme:
  name: material
  language: zh
  font: false
  favicon: assets/favicon.png
  logo: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 切换到亮色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: 切换到暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: 根据系统自动
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
extra:
  social:
    - icon: fontawesome/brands/qq
      link: https://qm.qq.com/q/3g6zkKdta8
    - icon: fontawesome/brands/discord
      link: https://discord.gg/fluxhvh

nav:
  - 主页: index.md
  - 续费教程:
      - Fatality续费教程: guides/fatality-renewal-guide.md
      - Nixware续费教程: guides/nixware-renewal-guide.md
      - Neverlose续费教程: guides/neverlose-renewal-guide.md
      - Plague续费教程: guides/plague-renewal-guide.md
      - 人工自动续费教程: guides/manual-renewal-guide.md
  - 常见问题:
      - 如何查找订单号: faq/how-to-find-order-number.md
      - 服务器空枪问题: faq/missing-shots-in-server.md
      - 模型无法正常显示: faq/models-not-showing.md
  - Gamesense:
      - Gamesense售前教程: gamesense/before-buy-gamesense.md
      - Gamesense售后教程: gamesense/after-buy-gamesense.md
      - Gamesense常见问题: gamesense/gamesense-faq.md